version: "3.5"

services:
  mt2-erigon-master-1:
    image: cdk-erigon-abc:latest
    command: --config /usr/local/config.yaml
    environment:
      - name=value
    ports: 
      - "18545:8545"
    volumes:
      - ./data/docker/erigon-data-master-1-data:/home/erigon/.local/share/erigon
      - ./docker-config/hermezconfig-merlin-v2-testnet.yaml:/usr/local/config.yaml
    restart: unless-stopped
    mem_swappiness: 0
  mt2-erigon-master-2:
    image: cdk-erigon-abc:latest
    command: --config /usr/local/config.yaml
    environment:
      - name=value
    ports:
      - "18546:8545"
    volumes:
      - ./data/docker/erigon-data-master-2-data:/home/erigon/.local/share/erigon
      - ./docker-config/hermezconfig-merlin-v2-testnet.yaml:/usr/local/config.yaml
    restart: unless-stopped
    mem_swappiness: 0
  mt2-erigon-master-3:
    image: cdk-erigon-abc:latest
    command: --config /usr/local/config.yaml
    environment:
      - name=value
    ports:
      - "18547:8545"
      - "10220:10220"
    volumes:
      - ./data/docker/erigon-data-master-3-data:/home/erigon/.local/share/erigon
      - ./docker-config/hermezconfig-merlin-v2-testnet.yaml:/usr/local/config.yaml
    restart: unless-stopped
    mem_swappiness: 0
  mt2-erigon-expand-1-1:
    image: cdk-erigon-abc:latest
    command: --config /usr/local/config.yaml --zkevm.l2-datastreamer-url=mt2-erigon-master-1:10220
    environment:
      - name=value
    ports:
      - "18645:8545"
    volumes:
      - ./data/docker/erigon-data-expand-1-1-data:/home/erigon/.local/share/erigon
      - ./docker-config/hermezconfig-merlin-v2-testnet.yaml:/usr/local/config.yaml
    restart: unless-stopped
    mem_swappiness: 0
  mt2-erigon-expand-2-1:
    image: cdk-erigon-abc:latest
    command: --config /usr/local/config.yaml --zkevm.l2-datastreamer-url=mt2-erigon-master-2:10220
    environment:
      - name=value
    ports:
      - "18646:8545"
    volumes:
      - ./data/docker/erigon-data-expand-2-1-data:/home/erigon/.local/share/erigon
      - ./docker-config/hermezconfig-merlin-v2-testnet.yaml:/usr/local/config.yaml
    restart: unless-stopped
    mem_swappiness: 0
